# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:latest
WORKDIR /app

#install deps
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

#Copy source code
COPY . .


ENTRYPOINT [ "bun", "run", "dev" ]
