
services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./data:/data
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend/Containerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend